---
title: MAMBO Horizon WP4 - RSE Talk 
author:
  name: Jo Walsh
  affiliation: UK Centre for Ecology & Hydrology
  email: jowals@ceh.ac.uk
  orcid: 0000-0003-0268-2263
date: last-modified
date-format: long
abstract: |
    Presentation from a Research Software Engineer on the work involved making MAMBO code and data portable and reusable, with potential lessons for future effort
bibliography: references.bib
---

:::: {.content-visible when-format="html" unless-format="revealjs"}
:::{.callout-tip}
Toggle between light and dark mode using the switch in the top-right corner.
:::
::::

## Overview 

* Being late to the project
* Making code and data more reusable
* Dreams and challenges

## WP4 - shrub attributes from drone data

* Deep learning model (Attention Unet) for shrub shapes 
* Methods for attributing heights that feed into biomass calculations
* Turning research prototypes into workshop material
* Preparing and documenting data! 

## Start with data 

* [Data Management Plan](https://www.ceh.ac.uk/news-and-media/blogs/implementing-fair-wizard-ukceh)
* ???
* Deliverables

## Create shared archives

* Researchers have local, duplicate copies
* Data wants to live where the compute is!
* Everyone has their own complex needs

## Cloud storage

* [guide.cloudnativegeo.org](https://guide.cloudnativegeo.org)
* Built-in readers in open source libraries
* Lucky to have [JASMIN](https://jasmin.ac.uk/) offering s3 in the UK

## Ideals 

* STAC catalogue for metadata and query
* Like [Microsoft's Planetary Computer](https://planetarycomputer.microsoft.com)
* [Pangeo @ EOSC](https://pangeo-eosc.vm.fedcloud.eu/)

## Challenges

* Our storage is time-limited to the project funded phase
* Zenodo is lovely for archiving, but is it meant for programmatic reuse?

## Reproducible, reusable code

* From research prototype to installable package
* [EVERSE.eu](https://everse.software/)
* Continuously-running tests; simple packaging

## Challenges 1

* More LLM-generated code
* If it must happen, generate tests, pipelines and packaging too
* Tried it both ways, took about the same time

## Challenges 2

* Reproducible environments
* Making dependencies easy to install
* Keeping notebooks and packages in sync


## Portability

* Move out of personal projects to a shared Organisation
* Futureproof against people moving on
* [ICAERUS](https://icaerus.eu/) offer a shared model for this

## Adaptability


## More information

[MAMBO Horizon WP4 on Github](https://github.com/MAMBO-Horizon-WP4/)

